POST http://127.1.1.1:8082/register
Accept: */*
Cache-Control: no-cache

{"Username": "vlad_e_hispter@gmail.com", "Password": "notarealpasswordjustthehash"}

####

#POST http://127.1.1.1:8082/authenticate
#Accept: */*
#Cache-Control: no-cache
#
#{"Username": "vlad_e_hispter@gmail.com", "Password": "notarealpasswordjustthehash"}


###
#
#POST http://127.1.1.1:8082/modifypassword
#Authentication: Bearer AAA.BBB.CCC
#Accept: */*
#Cache-Control: no-cache
#
#{"Username": "vlad_e_hispter@gmail.com", "OldPassword": "notarealpasswordjustthehash", "NewPassword": "newpasswordhash"}

####
#
#POST http://127.1.1.1:8082/getaccounts
#Authentication: Bearer AAA.BBB.CCC
#Accept: */*
#Cache-Control: no-cache


####
#
#POST http://127.1.1.1:8082/modifyaccount
#Authentication: Bearer AAA.BBB.CCC
#Accept: */*
#Cache-Control: no-cache
#
#{"Operation": "add", "Site": {"Username": "vlad_e_hipster@gmail.com", "Password": "nohackerpls", "Id": "faranumar"}}
####
